source("../datos/read_data.R")
setwd("~/MEGA/MEGAsync/DATA-SCIENCE/work/c4-w1-project/1graphs")
par(mfrow=c(1,1))
plot(pow_consumption$DateTime, pow_consumption$Sub_metering_1,ylab="Energy Sub Metering", type='l',xlab=" ",col="black")
lines(pow_consumption$DateTime,pow_consumption$Sub_metering_2,col="red")
lines(pow_consumption$DateTime,pow_consumption$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),lty="solid")
dev.copy(png,"Plot3.png",width=480,height=480,units='px')
dev.off()